# Generated by Django 6.0.2 on 2026-02-27 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ifmisresetrequest_reference_code_requestmessage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RequestMessage',
            new_name='IFMISRequestMessage',
        ),
    ]
