# Generated by Django 6.0.2 on 2026-02-27 21:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_requestmessage_ifmisrequestmessage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('LOGIN', 'Logged In'), ('LOGOUT', 'Logged Out'), ('VIEW_REQUEST', 'Viewed Request'), ('MARK_PROCESSED', 'Marked as Processed'), ('MARK_PENDING', 'Reverted to Pending'), ('SEND_REPLY', 'Sent Reply'), ('DELETE_REQUEST', 'Deleted Request'), ('BULK_DELETE', 'Bulk Deleted Requests')], max_length=30)),
                ('ref_code', models.CharField(blank=True, max_length=12, null=True)),
                ('detail', models.TextField(blank=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('admin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
    ]
